GET http://localhost:8080/day/2020-07-14

###
POST http://localhost:8080/day
Content-Type: application/json

{"description":  "a new task is added", "duration":  60, "date": "2020-07-14T07:12:24"}

###
GET http://localhost:8080/week/2020-07-14

###
DELETE http://localhost:8080/day/11

###
PUT http://localhost:8080/task/1
Content-Type: application/json

{"description":  "this is an edited task", "duration":  60, "date": "2020-07-14T16:38:24"}