GET http://localhost:8080/day/2020-07-18

###
POST http://localhost:8080/day
Content-Type: application/json

{"description":  "testing task service", "duration":  50, "date": "2020-07-18T09:22:24"}

###
GET http://localhost:8080/week/2020-07-14

###
DELETE http://localhost:8080/task/20

###
PUT http://localhost:8080/task/1
Content-Type: application/json

{"description":  "this is an edited task", "duration":  60, "date": "2020-07-14T16:38:24"}